# taps
tap "homebrew/cask" || true
tap "homebrew/cask-fonts" || true

# cask
cask_args appdir: "/Applications"

# browsers
cask "google-chrome"

# editors
cask "intellij-idea-ce"
cask "visual-studio-code"
brew "neovim"

# fonts
cask "font-hasklig"

# languages
cask "adoptopenjdk/openjdk/adoptopenjdk8"
brew "maven"
brew "gradle"
brew "node"
brew "elixir"
brew "elm"
brew "elm-format"

# socials
cask "telegram"
cask "slack"

# terminal
cask "iterm2"
brew "antigen"
brew "git"
brew "hub"
brew "tig"
brew "diff-so-fancy"
brew "autojump"
brew "git-extras"
brew "the_silver_searcher"
brew "tree"
brew "bat"
brew "tldr"
brew "jq"
brew "ncdu"
brew "pidof"
brew "htop"
brew "httpie"
brew "fzf"

# ui
cask "dozer"
cask "flux"

# utils
cask "rectangle"
cask "jumpcut"
cask "tomighty"
cask "ngrok"
cask "mos"
cask "docker"
cask "karabiner-elements"
cask "unclack"

# productivity
brew "ical-buddy"