#!/bin/bash

# asdf
asdf plugin add java
asdf plugin add erlang
asdf plugin add elixir
asdf plugin add elm
asdf plugin add nodejs
asdf plugin add elixir
asdf plugin add python
asdf plugin add rust
asdf install

# visual studio code
code --install-extension akamud.vscode-theme-onedark
code --install-extension pkief.material-icon-theme

code --install-extension formulahendry.auto-rename-tag
code --install-extension aaron-bond.better-comments
code --install-extension alefragnani.bookmarks
code --install-extension coenraads.bracket-pair-colorizer
code --install-extension wmaurer.change-case
code --install-extension formulahendry.code-runner
code --install-extension ms-azuretools.vscode-docker
code --install-extension eamodio.gitlens
code --install-extension mhutchie.git-graph
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-audio
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension christian-kohler.path-intellisense
code --install-extension pnp.polacode
code --install-extension mohsen1.prettify-json
code --install-extension alefragnani.project-manager
code --install-extension ms-vscode-remote.remote-containers
code --install-extension cssho.vscode-svgviewer
code --install-extension bibhasdn.unique-lines
code --install-extension dotjoshjohnson.xml

code --install-extension jakebecker.elixir-ls
code --install-extension elmtooling.elm-ls-vscode
code --install-extension fwcd.kotlin
code --install-extension ms-python.python
code --install-extension mjmcloug.vscode-elixir

# neovim
curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +PlugInstall +qall

# iterm
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/dotfiles/conf/dots/iterm2"

# zsh
sudo chsh -s $(which zsh) $(whoami)

# flux
defaults write org.herf.Flux dayColorTemp 5800
defaults write org.herf.Flux nightColorTemp 3800
defaults write org.herf.Flux lateColorTemp 2700

# jumpcut
defaults write net.sf.Jumpcut "ShortcutRecorder mainHotkey" '{ "keyCode" = 9 ; "modifierFlags" = 1179648; }'

# tomighty
defaults write org.tomighty.Tomighty org.tomighty.enable_notifications 0
defaults write org.tomighty.Tomighty org.tomighty.hotkey.start "^\\U2325\\U2318P"
defaults write org.tomighty.Tomighty org.tomighty.hotkey.stop "^\\U2325\\U2318S"
defaults write org.tomighty.Tomighty org.tomighty.sound.play_tick_tock_during_break 0
defaults write org.tomighty.Tomighty org.tomighty.sound.play_tick_tock_during_pomodoro 0
defaults write org.tomighty.Tomighty org.tomighty.general.status_icon_time_format 1

# mos
defaults write com.caldis.Mos reverse 0
defaults write com.caldis.Mos step 40
defaults write com.caldis.Mos speed 3
defaults write com.caldis.Mos duration 4.3

# rectangle
defaults write com.knollsoft.Rectangle bottomHalf '{ keyCode = 125; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle bottomLeft '{ keyCode = 40; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle bottomRight '{ keyCode = 37; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle center '{ keyCode = 8; modifierFlags = 1835008; }'
defaults write com.knollsoft.Rectangle leftHalf '{ keyCode = 123; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle maximize '{ keyCode = 3; modifierFlags = 1835008; }'
defaults write com.knollsoft.Rectangle rightHalf '{ keyCode = 124; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topHalf '{ keyCode = 126; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topLeft '{ keyCode = 34; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topRight '{ keyCode = 31; modifierFlags = 1310720; }'
