#!/bin/bash

# visual studio code
code --install-extension akamud.vscode-theme-onedark
code --install-extension pkief.material-icon-theme
code --install-extension mjmcloug.vscode-elixir
code --install-extension eamodio.gitlens
code --install-extension ms-azuretools.vscode-docker

# neovim
curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +PlugInstall +qall

# iterm
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "$HOME/dotfiles/conf/dots/iterm2"

# zsh
sudo chsh -s $(which zsh) $(whoami)

# flux
defaults write org.herf.Flux dayColorTemp 5800
defaults write org.herf.Flux nightColorTemp 3800
defaults write org.herf.Flux lateColorTemp 2700

# jumpcut
defaults write net.sf.Jumpcut "ShortcutRecorder mainHotkey" '{ "keyCode" = 9 ; "modifierFlags" = 1179648; }'

# tomighty
defaults write org.tomighty.Tomighty org.tomighty.enable_notifications 0
defaults write org.tomighty.Tomighty org.tomighty.hotkey.start "^\\U2325\\U2318P"
defaults write org.tomighty.Tomighty org.tomighty.hotkey.stop "^\\U2325\\U2318S"
defaults write org.tomighty.Tomighty org.tomighty.sound.play_tick_tock_during_break 0
defaults write org.tomighty.Tomighty org.tomighty.sound.play_tick_tock_during_pomodoro 0
defaults write org.tomighty.Tomighty org.tomighty.general.status_icon_time_format 1

# mos
defaults write com.caldis.Mos reverse 0
defaults write com.caldis.Mos step 40
defaults write com.caldis.Mos duration 4.3

# rectangle
defaults write com.knollsoft.Rectangle bottomHalf '{ keyCode = 125; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle bottomLeft '{ keyCode = 40; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle bottomRight '{ keyCode = 37; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle center '{ keyCode = 8; modifierFlags = 1835008; }'
defaults write com.knollsoft.Rectangle leftHalf '{ keyCode = 123; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle maximize '{ keyCode = 3; modifierFlags = 1835008; }'
defaults write com.knollsoft.Rectangle rightHalf '{ keyCode = 124; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topHalf '{ keyCode = 126; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topLeft '{ keyCode = 34; modifierFlags = 1310720; }'
defaults write com.knollsoft.Rectangle topRight '{ keyCode = 31; modifierFlags = 1310720; }'